framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        headers:
            From: 'Contact <contact@bien-etre-equin.com>'
            To: ['lucile.schuler@bien-etre-equin.com']
        
                    

